mongodb:
  architecture: replicaset
  auth:
    rootUser: root
    rootPassword: Password123
  replicaCount: 2
  replicaSetName: "rs0"
  replicaSetKey: "/opt/bitnami/mongodb/conf/keyfile"
  resources:
    requests:
      memory: "2Gi"

nx-cloud:
  imageTag: latest
  # plain auth
  auth:
    adminPassword: Password123
  # creates secret for plain auth
  secret:
    name: nx-cloud-secret
  nxCloudAppURL: https://nx.example.com

ingress:
  tls:
    - hosts:
        - nx.example.com
      secretName: nx.example.com-cert

metallb:
  enabled: true
  ipAddressPool:
    addresses:
      - 192.168.178.240-192.168.178.240
    autoAssign: true
