apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nx-cloud-ingress
  labels:
    app: nx-cloud
spec:
  ingressClassName: nginx
  rules:
    - host: {{ index .Values "nx-cloud" "nxCloudAppURL" | replace "https://" "" | replace "http://" "" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-frontend-service
                port:
                  number: 8080
          - path: /file
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-file-server-service
                port:
                  number: 5000
          - path: /nx-cloud
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-nx-api-service
                port:
                  number: 4203
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-nrwl-api-service
                port:
                  number: 4000
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-nrwl-api-service
                port:
                  number: 4000
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-nrwl-api-service
                port:
                  number: 4000
          - path: /download
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-nrwl-api-service
                port:
                  number: 4000                
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 2}}
{{- end -}}