{{ $releaseName := .Release.Name }}
{{- if .Values.metallb.enabled }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $releaseName }}-local-ip-pool
  annotations:
    "helm.sh/hook": post-install # todo delete on uninstall etc
    "helm.sh/hook-weight": "-5"
spec:
{{ toYaml .Values.metallb.ipAddressPool | indent 2 }}

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  ipAddressPools:
  - {{ $releaseName }}-local-ip-pool
{{- end }}