{{- $nxCloudAuth := index .Values "nx-cloud" "auth" -}}
{{- $nxCloudSecret := index .Values "nx-cloud" "secret" -}}
{{- $mongodbCloudAuth := index .Values.mongodb.auth -}}
{{ if and $nxCloudAuth $nxCloudSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $nxCloudSecret.name }}
  annotations:
    "helm.sh/hook": pre-install # todo delete on uninstall etc
    "helm.sh/hook-weight": "-5"
type: Opaque
stringData:
  NX_CLOUD_MONGO_SERVER_ENDPOINT: 'mongodb://{{ $mongodbCloudAuth.rootUser }}:{{ $mongodbCloudAuth.rootPassword }}@{{ .Release.Name }}-mongodb-headless.default.svc.cluster.local/nrwl-api?authSource=admin'
  ADMIN_PASSWORD: {{ $nxCloudAuth.adminPassword | quote }}
{{ end }}