{{- $githubAuth := index .Values "github" "auth" -}}
{{- $nxCloudSecret := index .Values "nx-cloud" "secret" -}}
{{- $mongodbCloudAuth := index .Values.mongodb.auth -}}
{{ if $nxCloudSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $nxCloudSecret.name }}
  annotations:
    "helm.sh/hook": pre-install # todo delete on uninstall etc
    "helm.sh/hook-weight": "-5"
type: Opaque
stringData:
  GITHUB_AUTH_CLIENT_ID: {{ $githubAuth.clientId | quote }}
  GITHUB_AUTH_CLIENT_SECRET: {{ $githubAuth.clientSecret | quote }}
  NX_CLOUD_MONGO_SERVER_ENDPOINT: mongodb://{{ $mongodbCloudAuth.rootUser }}:{{ $mongodbCloudAuth.rootPassword }}@{{ .Release.Name }}-mongodb-0.{{ .Release.Name }}-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local:27017,{{ .Release.Name }}-mongodb-1.{{ .Release.Name }}-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local:27017/nrwl-api?replicaSet=rs0&readPreference=primary&authSource=admin&authMechanism=SCRAM-SHA-256
{{ end }}