apiVersion: v1
kind: Secret
metadata:
  name: nx-cloud-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: Opaque
stringData:
  NX_CLOUD_MONGO_SERVER_ENDPOINT: mongodb://{{ .Values.mongodb.auth.rootUser }}:{{ .Values.mongodb.auth.rootPassword }}@{{ .Release.Name }}-nx-cloud-mongodb.default.svc.cluster.local/nrwl-api?authSource=admin
  ADMIN_PASSWORD: {{ index .Values "nx-cloud" "adminPassword" }}
